name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_preview:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          cache: 'npm'
      - name: 'Checking the code using a linter'
        run: npm ci && npm run eslint
