name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  username: ${{ secrets.DOCKERHUB_USERNAME }}
  password: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build_and_preview:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          cache: 'npm'
      - name: 'Checking the code using a linter'
        run: npm ci && npm run eslint
      
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: $username
          password: $password
          
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
        
      - name: 'Build and push'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $username/clockbox:latest

