name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCK_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCK_PASS: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build_and_preview:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          cache: 'npm'
      - name: 'Checking the code using a linter'
        run: npm ci && npm run eslint
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: 'Docker image build'
        run: docker build . --file Dockerfile --tag $DOCKER_USER/node_app_docker:${{ steps.date.outputs.date }}

      - name: docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: 'Push Docker image to Docker Hub'
        run: docker push $DOCKER_USER/node_app_docker:${{ steps.date.outputs.date }}
